service: sfsu-csc648-team04
image: sfsu-csc648-06-fall26-team04
minimum_version: 2.12.0

servers:
  web:
    - 159.198.74.249

proxy:
  app_port: 6767
  healthcheck:
    path: /up

registry:
  server: localhost:5555

builder:
  arch: amd64

ssh:
  user: student
  forward_agent: false
